-- AlterTable
ALTER TABLE "CarReport" ADD COLUMN     "defects" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "expertNotes" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "paintScore" INTEGER NOT NULL DEFAULT 7,
ALTER COLUMN "tiresScore" SET DEFAULT 7,
ALTER COLUMN "electricsScore" SET DEFAULT 7,
ALTER COLUMN "expertOverallScore" SET DATA TYPE DECIMAL(4,2),
ALTER COLUMN "platformScore" SET DATA TYPE DECIMAL(4,2);
